
services:
  clapshot:
    image: elonen/clapshot:latest-demo-htadmin
    container_name: clapshot_app
    ports:
      - 8080:80
    volumes:
      - clapshotdata:/mnt/clapshot-data/data



volumes:
  clapshotdata: