
services:
  clapshot:
    build:
      context: .
#    image: pomerium/pomerium:latest
    #image: ghcr.io/mmo31/personalidentityawareproxy/pomerium:latest
    image: myclapshot
    pull_policy: build
    container_name: clapshot_app
    ports:
      - 8092:8080
    volumes:
      - clapshotdata:/mnt/clapshot-data/data
    environment:
      - PUBLIC_ADDRESS=https://clapshot.mollin.fr
    restart: unless-stopped



volumes:
  clapshotdata: