
services:
  clapshot:
    image: elonen/clapshot:latest-demo-htadmin
    container_name: clapshot_app
    ports:
      - "8080:8080"
    volumes:
      - clapshotdata:/mnt/clapshot-data/data
    network_mode: bridge


volumes:
  clapshotdata: