
services:
  clapshot:
    build:
      context: .
#    image: pomerium/pomerium:latest
    #image: ghcr.io/mmo31/personalidentityawareproxy/pomerium:latest
    image: myclapshot
    container_name: clapshot_app
    ports:
      - 8092:80
    volumes:
      - clapshotdata:/mnt/clapshot-data/data



volumes:
  clapshotdata: