
services:
  clapshot:
    image: clapshot:latest
    container_name: clapshot_app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/clapshotdb
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: clapshot_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: clapshotdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: